add ability to deploy using default hardhat method
needed because polygon mainnet contract deployments are not going through.

traceback:

Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":53,\"error\":{\"code\":-32000,\"message\":\"transaction underpriced\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":

requestMethod: 'POST',
  url: 'https://polygon-rpc.com',
  transaction: {
    type: 2,
    chainId: 137,
    nonce: 4,
    maxPriorityFeePerGas: BigNumber { _hex: '0x9502f900', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x9502fb04', _isBigNumber: true },
    gasPrice: null,
    gasLimit: BigNumber { _hex: '0x1181a5', _isBigNumber: true },
    to: null,
    value: BigNumber { _hex: '0x00', _isBigNumber: true },